let state={chat_completions:[],responses:[]};
let savedState={chat_completions:[],responses:[]};
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function rowSnapshot(x){return {id:x.id,public_model:x.public_model,url:x.url,key:x.key,upstream_model:x.upstream_model,use_proxy:x.use_proxy,proxy_from_chat_completions:x.proxy_from_chat_completions,enabled:x.enabled}}
function isRowSaved(type,x){const saved=(savedState[type]||[]).find(y=>y.id===x.id);return !!saved&&JSON.stringify(rowSnapshot(saved))===JSON.stringify(rowSnapshot(x))}
function section(type,title){const a=state[type]||[];return '<div class="card"><div class="head"><h2>'+title+'</h2><button class="btn secondary" onclick="addRow(\''+type+'\')">+ 添加</button></div><div class="hint">公开模型名 → 上游地址 / Key / 上游模型名 / 代理</div><div id="rows-'+type+'">'+(a.length?a.map((x,i)=>row(type,x,i)).join(''):'<div class="empty">还没有配置。</div>')+'</div></div>'}
function row(type,x,i){const rid='result-'+type+'-'+i;const responseOption=type==='responses'?'<label class="check"><input type="checkbox" '+(x.proxy_from_chat_completions===true?'checked':'')+' onchange="edit(\''+type+'\','+i+',\'proxy_from_chat_completions\',this.checked)">从 Chat Completions 代理</label>':'';const testButton=isRowSaved(type,x)?'<button class="btn secondary" onclick="testRow(\''+type+'\','+i+')">测试“你好”</button>':'';return '<div class="row"><input placeholder="公开模型名，如 gpt-4" value="'+esc(x.public_model)+'" oninput="edit(\''+type+'\','+i+',\'public_model\',this.value)"><input placeholder="接口地址，如 https://.../v1/chat/completions" value="'+esc(x.url)+'" oninput="edit(\''+type+'\','+i+',\'url\',this.value)"><input type="password" placeholder="API Key" value="'+esc(x.key)+'" oninput="edit(\''+type+'\','+i+',\'key\',this.value)"><input placeholder="上游模型名" value="'+esc(x.upstream_model)+'" oninput="edit(\''+type+'\','+i+',\'upstream_model\',this.value)"><label class="check"><input type="checkbox" '+(x.use_proxy!==false?'checked':'')+' onchange="edit(\''+type+'\','+i+',\'use_proxy\',this.checked)">SOCKS5</label>'+responseOption+testButton+'<button class="btn danger" onclick="delRow(\''+type+'\','+i+')">删除</button><div id="'+rid+'" class="result" style="display:none"></div></div>'}
function edit(t,i,k,v){state[t][i][k]=v;updateTestButtons(t)}
function updateTestButtons(t){const container=document.getElementById('rows-'+t);if(!container)return;(state[t]||[]).forEach((x,i)=>{const rowEl=container.children[i];if(!rowEl)return;const buttons=rowEl.querySelectorAll('button.btn.secondary');const resultButton=[...buttons].find(b=>b.textContent.includes('测试“你好”'));if(isRowSaved(t,x)){if(!resultButton){const delButton=rowEl.querySelector('button.btn.danger');const btn=document.createElement('button');btn.className='btn secondary';btn.textContent='测试“你好”';btn.onclick=()=>testRow(t,i);delButton.before(btn)}}else if(resultButton){resultButton.remove()}})}
function addRow(t){state[t].push({id:String(Date.now()+Math.random()),public_model:'',url:'',key:'',upstream_model:'',use_proxy:true,proxy_from_chat_completions:false,enabled:true});render()}
function delRow(t,i){state[t].splice(i,1);render()}
async function load(){state=await (await fetch('/api/config')).json();savedState=JSON.parse(JSON.stringify(state));render()}
async function save(){const r=await fetch('/api/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});if(!r.ok){flash('保存失败');return}state=await r.json();savedState=JSON.parse(JSON.stringify(state));render();flash('已保存')}
async function testRow(t,i){const x=state[t][i];if(!isRowSaved(t,x))return;const el=document.getElementById('result-'+t+'-'+i);el.style.display='block';el.className='result';el.textContent='测试中...';try{const r=await fetch('/api/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:t,id:x.id})});const d=await r.json();if(!r.ok)throw new Error(d.error||'测试失败');el.textContent='HTTP '+d.status+'\n'+d.text}catch(e){el.className='result error';el.textContent=e.message}}
function formatMs(v){return v==null?'—':v+' ms'}
function formatSpeed(r){if(r.tokens_per_second!=null)return r.tokens_per_second+' tok/s';if(r.chars_per_second!=null)return r.chars_per_second+' 字符/s';return '—'}
function renderBenchmark(results,running,live){const el=document.getElementById('benchmark-results');if(!results.length&&!running){el.className='empty';el.textContent='没有可测试的已启用配置。';return}let html='';if(running&&live){html+='<div class="bench-live"><div class="bench-live-title">正在测试 '+esc(live.model)+'</div><div class="bench-live-detail">'+esc(live.status)+(live.text?'\n流式返回内容`'+live.text.slice(-120)+'`':'')+'</div></div>'}if(!results.length){if(!running)html='<div class="empty">没有可测试的已启用配置。</div>';el.className='';el.innerHTML=html;return}html+='<table class="bench-table"><thead><tr><th>类型</th><th>模型</th><th>状态</th><th>首字延迟</th><th>生成速度</th><th>生成量</th><th>总耗时</th><th>回复</th></tr></thead><tbody>';for(const r of results){const ok=r.ok;const runningRow=r.running;html+='<tr><td>'+esc(r.type==='responses'?'Responses':'Chat Completions')+'</td><td><strong>'+esc(r.model)+'</strong>'+(r.upstream_model&&r.upstream_model!==r.model?'<div class="hint">→ '+esc(r.upstream_model)+'</div>':'')+'</td><td class="'+(runningRow?'bench-running':ok?'bench-ok':'bench-error')+'">'+(runningRow?'测试中…':ok?'完成':'失败')+(r.status?' · HTTP '+r.status:'')+(r.error?'<div>'+esc(r.error)+'</div>':'')+'</td><td class="metric">'+formatMs(r.ttft_ms)+'</td><td class="metric">'+formatSpeed(r)+(r.completion_tokens!=null?' <span class="hint">('+r.completion_tokens+' tok)</span>':'')+'</td><td class="metric">'+(r.generated_chars!=null?r.generated_chars+' 字符':'—')+'</td><td class="metric">'+formatMs(r.total_ms)+'</td><td><div class="bench-text">'+esc(r.text||'')+'</div></td></tr>'}html+='</tbody></table>';const done=results.filter(r=>!r.running).length;const failed=results.filter(r=>!r.running&&!r.ok).length;el.className='';el.innerHTML=html+(done?'<div class="bench-summary">已完成 '+done+' 个配置'+(failed?'，失败 '+failed+' 个':'')+'。TTFT 从请求发出开始计算，到收到第一个文本增量为止；生成速度优先使用上游返回的 completion/output tokens 计算，否则显示字符/秒。</div>':'')}
function benchmarkPrompt(){return '请用中文写一段约两百字的完整回复，主题是“为什么人工智能值得学习”。只输出正文，不要标题、列表、Markdown、前言或结语说明。请尽量接近两百字。'}
async function readBenchmarkStream(type,model,onUpdate){const startedAt=performance.now();let firstTextAt=null,text='',buffer='',usage=null,status=0;const body=type==='responses'?{model,input:benchmarkPrompt(),stream:true,max_output_tokens:500}:{model,messages:[{role:'user',content:benchmarkPrompt()}],stream:true,max_tokens:500};onUpdate({status:'等待'+model+'模型返回首字'});const response=await fetch(type==='responses'?'/v1/responses':'/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Accept':'text/event-stream'},body:JSON.stringify(body)});status=response.status;if(!response.ok){let msg='HTTP '+response.status;try{const d=await response.json();msg=d.error?.message||msg}catch{}throw new Error(msg)};if(!response.body)throw new Error('浏览器不支持流式响应');onUpdate({status:'已连接，等待'+model+'模型返回首字'});const reader=response.body.getReader();const decoder=new TextDecoder();const consume=(chunk)=>{buffer+=chunk;const lines=buffer.split(/\r?\n/);buffer=lines.pop()||'';for(const line of lines){if(!line.startsWith('data:'))continue;const raw=line.slice(5).trim();if(!raw||raw==='[DONE]')continue;let data;try{data=JSON.parse(raw)}catch{continue}let delta='';if(type==='responses'){if(typeof data.delta==='string'&&(data.type||'').includes('output_text'))delta=data.delta;else if(typeof data.output_text?.delta==='string')delta=data.output_text.delta}else delta=typeof data.choices?.[0]?.delta?.content==='string'?data.choices[0].delta.content:'';if(data.usage)usage=data.usage;if(delta){if(firstTextAt===null){firstTextAt=performance.now();onUpdate({status:'已返回首字，正在流式生成',ttft_ms:Math.round(firstTextAt-startedAt)})}text+=delta;onUpdate({status:'流式返回内容`'+text.slice(-120)+'`',text})}}};while(true){const {value,done}=await reader.read();if(done)break;consume(decoder.decode(value,{stream:true}))}consume(decoder.decode());const finishedAt=performance.now();const ttft=firstTextAt===null?null:firstTextAt-startedAt;const generationMs=firstTextAt===null?null:finishedAt-firstTextAt;const generatedChars=[...text].length;const completionTokens=usage?.completion_tokens??usage?.output_tokens??null;return {ok:true,status,ttft_ms:ttft==null?null:Math.round(ttft),total_ms:Math.round(finishedAt-startedAt),generation_ms:generationMs==null?null:Math.round(generationMs),generated_chars:generatedChars,chars_per_second:generationMs&&generatedChars?Math.round(generatedChars/(generationMs/1000)*10)/10:null,completion_tokens:completionTokens,tokens_per_second:completionTokens!=null&&generationMs>0?Math.round(completionTokens/(generationMs/1000)*10)/10:null,text}}
async function testAll(){const btn=document.getElementById('test-all');btn.disabled=true;btn.textContent='测试中…';const entries=[];for(const type of ['chat_completions','responses'])for(const entry of(state[type]||[])){if(entry.enabled===false||!entry.public_model||!entry.url)continue;const saved=(savedState[type]||[]).find(x=>x.id===entry.id);if(!saved||!isRowSaved(type,entry))continue;entries.push({type,model:entry.public_model,upstream_model:entry.upstream_model||entry.public_model})}let results=[];let live=null;renderBenchmark([],true,null);try{for(const item of entries){live={...item,status:'准备测试 '+item.model,text:''};renderBenchmark(results,true,live);let result;try{result=await readBenchmarkStream(item.type,item.model,(u)=>{live={...item,...live,...u};renderBenchmark(results,true,live)})}catch(e){result={ok:false,error:e.message,text:live.text||''}}results.push({...item,...result});live=null;renderBenchmark(results,results.length<entries.length,null)}renderBenchmark(results,false,null);flash('所有配置测试完成')}catch(e){const el=document.getElementById('benchmark-results');el.className='result error';el.textContent='批量测试失败：'+e.message;flash('批量测试失败')}finally{btn.disabled=false;btn.textContent='测试所有配置'}}
function flash(s){const el=document.getElementById('status');el.textContent=s;el.style.display='block';setTimeout(()=>el.style.display='none',1800)}
function render(){document.getElementById('app').innerHTML=section('chat_completions','Chat Completions')+section('responses','Responses')+'<div class="actions"><button class="btn" onclick="save()">保存配置</button><button class="btn secondary" onclick="load()">重新加载</button></div>'} load();
